### ISSUE TITLE
please help if it helps im on kali linux 

### ISSUE THREAD

**Issue by Deyelk** [ex0dus-0x/brut3k1t#1]
Traceback (most recent call last):
  File "brut3k1t.py", line 189, in <module>
    main()
  File "brut3k1t.py", line 169, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 17, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f4f37307890>> ignored

**Comment by ex0dus-0x** [comment]
Sorry for the late response. May I ask what your input was? Something that I will recommend you doing is reading the documentation, as well as pasting your error in Google for a search. I will review the code to see if I can raise this error and if i can fix it.

**Comment by ex0dus-0x** [comment]
For Kali users, please consider utilizing Firefox rather than the default Iceweasel.

**Comment by wermaxta** [comment]
i test it for facebook and is not working :))
