### ISSUE TITLE
hi I have this error when I use this command:

### ISSUE THREAD

**Issue by mysamvv** [ex0dus-0x/brut3k1t#101]
I have this error when I use this command:
./brut3k1t -s instagram -u test -w wordlist.txt -d 5

  _                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: test 
[*] Wordlist: wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/Desktop/brut3k1t-master/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t-master/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by ex0dus-0x** [comment]
Is Firefox installed?

This is a selenium issue, as it is not able to make a connection correctly to Firefox. Check to see if `firefox` and `geckodriver` are installed and in the `PATH`.

More information

* https://stackoverflow.com/questions/39547598/selenium-common-exceptions-webdriverexception-message-connection-refused
* https://stackoverflow.com/questions/39547598/selenium-common-exceptions-webdriverexception-message-connection-refused
