### ISSUE TITLE
Please help me with this problem.

### ISSUE THREAD

**Issue by HoroKasin** [ex0dus-0x/brut3k1t#103]
Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-i686/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.13.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.13.0-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
Unable to resolve the problem. Please help me.

**Comment by ex0dus-0x** [comment]
If you have read the `README`, you must retrieve a copy of `geckodriver`, and place it within your `PATH`. Since I have removed the `installer` script, this must be done manually.
