### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmp2cLkhS If you specified a log_file in the FirefoxBinary constructor, check it for details.

### ISSUE THREAD

**Issue by wermaxta** [ex0dus-0x/brut3k1t#15]
My OS kali linux  when i type 
python brut3k1t.py
Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from mainLib import *
  File "src/mainLib.py", line 24, in <module>
    import smtplib, argparse, paramiko, skpy, mechanize
  File "/usr/local/lib/python2.7/dist-packages/skpy/__init__.py", line 6, in <module>
    from skpy.util import SkypeUtils
  File "/usr/local/lib/python2.7/dist-packages/skpy/util.py", line 7, in <module>
    from .conn import SkypeConnection
  File "/usr/local/lib/python2.7/dist-packages/skpy/conn.py", line 9, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

if i type 
python3 brut3k1t.py
ile "brut3k1t.py", line 34
    print R + "[!] You have to specify a username AND a wordlist! [!]" + W
          ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by wermaxta** [comment]
and i make install
sudo python installer.py

**Comment by wermaxta** [comment]
on python 2.7 i got this error
python brut3k1t.py
Traceback (most recent call last):
File "brut3k1t.py", line 11, in
from mainLib import *
File "src/mainLib.py", line 24, in
import smtplib, argparse, paramiko, skpy, mechanize
File "/usr/local/lib/python2.7/dist-packages/skpy/init.py", line 6, in
from skpy.util import SkypeUtils
File "/usr/local/lib/python2.7/dist-packages/skpy/util.py", line 7, in
from .conn import SkypeConnection
File "/usr/local/lib/python2.7/dist-packages/skpy/conn.py", line 9, in
from bs4 import BeautifulSoup
File "build/bdist.linux-x86_64/egg/bs4/init.py", line 30, in
File "build/bdist.linux-x86_64/egg/bs4/builder/init.py", line 314, in
File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in
AttributeError: 'module' object has no attribute '_base'

**Comment by ex0dus-0x** [comment]
Delete repository, reclone, and do installer again.

Just made updates.

**Comment by wermaxta** [comment]
new problem i get this message

[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 193, in <module>
    main()
  File "brut3k1t.py", line 172, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmp2cLkhS If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by ex0dus-0x** [comment]
If you are using `firefox`, uninstall it and try with `firefox-esr`. 

Are you sure you have utilized the `installer.py` script? The `selenium` module from pip doesn't seem to work, so you need to have `python-selenium` installed instead. Remove `selenium` with:

    pip uninstall selenium

**Comment by wermaxta** [comment]
hi i make this pip uninstall selenium
and now is working 👍
