### ISSUE TITLE
Stuck on "[*]Checking if Username Exists. . . "

### ISSUE THREAD

**Issue by 5P4D3** [ex0dus-0x/brut3k1t#19]

**Comment by ex0dus-0x** [comment]
Please provide information. What is your operating system? What did you input in specifically? What protocol/service are you attempting to bruteforce? Did you run the `installer.py` script corresponding to your operating system? You need to give me something to work with.

**Comment by 5P4D3** [comment]
I already did the trouble shooting when i encounter the errors but in my last test this is my inputs dat im stuck in.. BTW i already run the installer.py and pip install -r requirements.txt and it was successful, so this is my command dat i used and stuck on Checking username exists. .

~ sudo python brut3k1t.py -s facebook -u myemail@email.com -w wordlist.txt
~ python brut3k1t.py -s facebook -u myemail@email.com -w wordlist.txt
~ python brut3k1t.py -s facebook -u myusername -w wordlist.txt
~ sudo python brut3k1t.py -s facebook -u myemail@email.com -w wordlist.txt

my firefox is opening and nothing happens and then its stuck on [*]Checking if username exists. . .
PS: No errors coming out. . . Sorry for my bad english. . .

**Comment by ex0dus-0x** [comment]
Instead of using an email address, switch to a username. For example, `myemail@email.com` might have the username `myusername` on Facebook. Try that instead. Usually, the person's Facebook username by going to their profile, and is listed in the URL.

**Comment by 5P4D3** [comment]
I Already try that too but then still stuck up on the Checking if username exists thing :(. . . .

**Comment by ex0dus-0x** [comment]
You have not told me what operating system. My method of diagnosing this issue is dependent on what OS you are using.

**Comment by 5P4D3** [comment]
Sorry Bro, Im Using Ubuntu 16.10. . . .

**Comment by ex0dus-0x** [comment]
When you ran the `installer.py` script, did you select either option 2) or 3)? I'm sure that are your dependencies are installed, but I want to make sure.

To make sure selenium is working and updated correctly:

    pip install -U selenium

Also, are you sure you are providing the correct username? If you go to a person's profile, it is usually found in the url, for e.g https://facebook.com/test_user , where test_user is their username.

I do not condone any sort of illegal activities, keep in mind. I really hope you aren't attempting to hack someone without consent.

**Comment by 5P4D3** [comment]
my selenium is up-to-date and i'm testing it on my own facebook account. and yet still stucking up on the Checking blah blah blah...

**Comment by ex0dus-0x** [comment]
Remove and reinstall Selenium with pip. Run the installer again. Make sure you have selected UBUNTU, not any of the other options. i386 (x86) and amd64 (x64) are your computer's architectures. Select the corresponding one to your computer.

Are there other browsers (for e.g Chromium) on the operating system? Did you receive any errors? Are you witnessing that Firefox opens up, but doesn't do anything, or is it that it is just plain stuck?

**Comment by 5P4D3** [comment]
Firefox opening up and its just a plain white when its open, i already tried reinstalling selenium, i have a chrome browser here... and i dont receive any errors dats why im having a hard time to identify the errors.

**Comment by ex0dus-0x** [comment]
Remove the Chrome browser. The reason you are not receiving any errors may be because of that.

**Comment by 5P4D3** [comment]
oh, maybe ill try it on my parrot security os... ill give you a report once i tested it on my parrot.

**Comment by ex0dus-0x** [comment]
Do a `git pull`. I have made minor edits. 

Please make sure you have `geckodriver` in your $PATH, specifically `/usr/bin`.

**Comment by Emadedden** [comment]
i canot open  brut3k1t pleaseh help me
This has appeared to me
==========================
 
Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from mainLib import *
  File "src/mainLib.py", line 26, in <module>
    import smtplib, argparse, paramiko, skpy, mechanize
ImportError: No module named skpy

**Comment by ex0dus-0x** [comment]
@Emadedden 

Really?

Have you read the README at all? Also open a new issue.

**Comment by ex0dus-0x** [comment]
@5P4D3 closing due to inactivity
