### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wermaxta** [ex0dus-0x/brut3k1t#2]
Hi my OS is kali linux 2016.2
Linux kali 4.8.0-kali1-amd64 #1 SMP Debian 4.8.5-1kali1 (2016-11-04) x86_64 GNU/Linux
when i type 
./brut3k1t.py -h
i get this 
raceback (most recent call last):
  File "./brut3k1t.py", line 8, in <module>
    from sshLib import *
  File "src/sshLib.py", line 1, in <module>
    import paramiko, sys, os, socket
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 60, in <module>
    from paramiko.ecdsakey import ECDSAKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/ecdsakey.py", line 26, in <module>
    from ecdsa import SigningKey, VerifyingKey, der, curves
ImportError: No module named ecdsa
OR
python brut3k1t.py -h 
Traceback (most recent call last):
  File "brut3k1t.py", line 8, in <module>
    from sshLib import *
  File "src/sshLib.py", line 1, in <module>
    import paramiko, sys, os, socket
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 60, in <module>
    from paramiko.ecdsakey import ECDSAKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/ecdsakey.py", line 26, in <module>
    from ecdsa import SigningKey, VerifyingKey, der, curves
ImportError: No module named ecdsa
OR
python brut3k1t.py 
Traceback (most recent call last):
  File "brut3k1t.py", line 8, in <module>
    from sshLib import *
  File "src/sshLib.py", line 1, in <module>
    import paramiko, sys, os, socket
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 60, in <module>
    from paramiko.ecdsakey import ECDSAKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/ecdsakey.py", line 26, in <module>
    from ecdsa import SigningKey, VerifyingKey, der, curves
ImportError: No module named ecdsa

so what is the problem :)

**Comment by wermaxta** [comment]
i fix it :))))

**Comment by wermaxta** [comment]
i test it for facebook and is not working :))

**Comment by ex0dus-0x** [comment]
Provide the Facebook user's ID, not their username. Please read the README file.

**Comment by wermaxta** [comment]
i put my Facebook ID and my password and i get this 
[*] Username: Facebook ID | [*] Password: Mypass | Incorrect!

**Comment by ex0dus-0x** [comment]
Hopefully the Facebook ID that you have provided looks like a string of numbers. If you did, I will test this again. Thanks for finding this.

**Comment by wermaxta** [comment]
so this is my facebook ID 100007897998908 and i get this
i also put my password in wordlist file
python brut3k1t.py -s facebook -u 100007897998908 -w wordlist.txt
*] Username: 100007897998908 
[*] Wordlist: wordlist.txt 
[*] Service: facebook 
[*] This Facebook bruteforce module is experimental. You will need to provide a Facebook ID instead of a username. Sorry! [*]
[*] Starting dictionary attack! [*]
Using 1 seconds of delay. Default is 1 second
Logging in...
Attempt #1 failed, retrying
Attempt #2 failed, retrying
Attempt #3 failed, retrying
Attempt #4 failed, retrying
Attempt #5 failed
[*] Username: 100007897998908 | [*] Password: replace | Incorrect!
*] Username: 100007897998908 | [*] Password: replace | Incorrect!

Logging in...
Attempt #1 failed, retrying
Attempt #2 failed, retrying
Attempt #3 failed, retrying
Attempt #4 failed, retrying
Attempt #5 failed
[*] Username: 100007897998908 | [*] Password: this | Incorrect!

Logging in...
Attempt #1 failed, retrying
Attempt #2 failed, retrying
Attempt #3 failed, retrying
Attempt #4 failed, retrying
Attempt #5 failed
[*] Username: 100007897998908 | [*] Password: MY PASSWORD | Incorrect!

**Comment by ex0dus-0x** [comment]
Update: I'm still working on the issue. For now, please do not rely on brut3k1t to bruteforce facebook! Thanks and sorry for the inconvenience!

**Comment by ssanonymous** [comment]
I get the same error on Kali Linux 32 bit VMware 9 on Windows 8.1 original Intel Pentium quad core...I don't know what is causing it...
Pls help

**Comment by ssanonymous** [comment]
./brut3k1t.py -h
i get this
raceback (most recent call last):
File "./brut3k1t.py", line 8, in 
from sshLib import *
File "src/sshLib.py", line 1, in 
import paramiko, sys, os, socket
File "/usr/local/lib/python2.7/dist-packages/paramiko/init.py", line 30, in 
from paramiko.transport import SecurityOptions, Transport
File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 60, in 
from paramiko.ecdsakey import ECDSAKey
File "/usr/local/lib/python2.7/dist-packages/paramiko/ecdsakey.py", line 26, in 
from ecdsa import SigningKey, VerifyingKey, der, curves

**Comment by ssanonymous** [comment]
./brut3k1t.py -h
i get this
raceback (most recent call last):
File "./brut3k1t.py", line 8, in 
from sshLib import *
File "src/sshLib.py", line 1, in 
import paramiko, sys, os, socket
File "/usr/local/lib/python2.7/dist-packages/paramiko/init.py", line 30, in 
from paramiko.transport import SecurityOptions, Transport
File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 60, in 
from paramiko.ecdsakey import ECDSAKey
File "/usr/local/lib/python2.7/dist-packages/paramiko/ecdsakey.py", line 26, in 
from ecdsa import SigningKey, VerifyingKey, der, curves
 This is the error
