### ISSUE TITLE
what this ?

### ISSUE THREAD

**Issue by zentany** [ex0dus-0x/brut3k1t#24]
my os kalilinux 2 

[*] Wordlist: /root/brut3k1t/wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 201, in <module>
    main()
  File "brut3k1t.py", line 165, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 21, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7fc60d9f98d0>> ignored

**Comment by ex0dus-0x** [comment]
The problem seems to be that you need `geckodriver`. I hope you are you Firefox, which is a gecko-based browser.

In order to fix this, `tar -xvf` the `.tar` file in the `deps` folder. Then move it to your `/usr/bin`, which is part of your PATH.

**Comment by bakista** [comment]
Traceback (most recent call last):
  File "brut3k1t.py", line 201, in <module>
    main()
  File "brut3k1t.py", line 165, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 21, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 140, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0xb3e6e16c>> ignored

**Comment by zentany** [comment]
how can i ? move what ?

**Comment by ex0dus-0x** [comment]
READ what I have written @bakista @zentany.

There is a `.tar` file in the `deps` folder of the brut3k1t directory. Untar the file, and move `geckodriver` into `/usr/bin`.

**Comment by ex0dus-0x** [comment]
Also, please ensure that `python-selenium` is installed with `apt-get`. it should have been installed when you ran the `installer.py` file and selected the `(1) Kali Linux ` option.

**Comment by zentany** [comment]
yes thanx bro it work :) and brutforce oky :) very very nice work pro >> sorry my english to bad 
i install  selenium==2.53.6 
 ?

**Comment by ex0dus-0x** [comment]
On Kali Linux it should be `python-selenium`. The Selenium module from python is not efficient for Kali operating systems.

**Comment by zentany** [comment]
yes my frind But stop working on facebook ? >>> twitter ok :) instagram ok :)

**Comment by ex0dus-0x** [comment]
I really hope you aren't doing anything illegal.

There are a few ways to bypass rate limits, but they aren't implemented in brut3k1t

**Comment by zentany** [comment]
I'm not doing anything illegal ... I try my penetration on My Account .... Can you tell me about it :)

**Comment by ex0dus-0x** [comment]
Tell you about what? 

This code is still under heavy development. This is a GitHub issue, not a forum. 

I don't think you really know how to write at least a minimal, formal issue: https://guides.github.com/features/issues/

Last of all, I really hope that [this](https://www.youtube.com/watch?v=A9UfAxgMGas) isn't your YouTube channel.

**Comment by zentany** [comment]
no not my channel >>> ok thanx

**Comment by Haidermahdi** [comment]
@ex0dus-0x  thanks i have seem problem and i fix it

**Comment by Tawbin-Raif** [comment]
how can i fix it?
Traceback (most recent call last):

  File "/usr/local/bin/brut3k1t", line 11, in <module>

    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()

  File "build/bdist.linux-i686/egg/brut3k1t/__main__.py", line 89, in main

  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 47, in execute

  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 56, in usercheck

  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 164, in __init__

    self.service.start()

  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start

    os.path.basename(self.path), self.start_error_message)

selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by Tawbin-Raif** [comment]
how can i fix it?


Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-i686/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
