### ISSUE TITLE
facebook bruts error

### ISSUE THREAD

**Issue by HassanAbdElaziz20** [ex0dus-0x/brut3k1t#25]
o
 \_/\o
( Oo)
(_=-)  .===O-  ~~Z~A~P~~ ~~Z~A~P~~
/   \_/U'
|
||  |_/     Stupid script kiddies!
\   |
{K ||
 | PP
 | ||
 (__\/

Welcome to brut3k1t!

[*] Username: Ph.EsraaEltouny
[*] Wordlist: /root/esraa.txt
[*] Service: facebook
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 201, in <module>
    main()
  File "brut3k1t.py", line 180, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by ex0dus-0x** [comment]
I really hope you are not doing anything illegal.

What operating system?

Have you closed the webbrowser after brut3k1t started running? Selenium is opening the web browser, so if you are closing it, don't do it.

**Comment by ex0dus-0x** [comment]
Due to inactivity, I will be closing this issue. Hope you got it resolved. Reopen if not.
