### ISSUE TITLE
Error ..

### ISSUE THREAD

**Issue by k6n** [ex0dus-0x/brut3k1t#26]
i get this error when i try to run it .. 
Traceback (most recent call last):
  File "brut3k1t.py", line 11, in <module>
    from mainLib import *
  File "src/mainLib.py", line 26, in <module>
    import smtplib, argparse, paramiko, skpy, mechanize
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: cannot import name decode_dss_signature

and if i try pip install -r requirements.txt i get ..
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

i went through the readme file step by step .. any suggestions ?

**Comment by ex0dus-0x** [comment]
What is your operating system? 

This is most likely an issue with dependencies with your `pip` and `requests` modules.

I have never seen this issue, but this is most likely an OS issue.

Refer here:
https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

https://stackoverflow.com/questions/34580806/pip3-importerror-cannot-import-name-incompleteread

**Comment by k6n** [comment]
Kali linux

**Comment by k6n** [comment]
solved by : apt-get remove pip and then easy_install pip ..
