### ISSUE TITLE
Some Problem raise when executing

### ISSUE THREAD

**Issue by derrickyin** [ex0dus-0x/brut3k1t#29]
Sorry to disturb you, may I know how to solve this problem? It appear when I run the command in terminal using MacOS. Thanks

[*] Username: test 
[*] Wordlist: wordlist.txt 
[*] Service: facebook 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 203, in <module>
    main()
  File "brut3k1t.py", line 180, in main
    if facebookCheck(username) == 1:
  File "src/facebookLib.py", line 19, in facebookCheck
    driver = webdriver.Firefox()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ex0dus-0x** [comment]
Although the `installer.py` script for macOS is tentatively supported, you can untar the `geckodriver` tar file in the `dist/` folder, and move the executable to `/usr/bin`. Also try reinstalling python selenium with `sudo easy_install selenium`.

**Comment by ueippp** [comment]
I gave it a try on mac ox howver I am getting the following expection:

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/selenium'

I have followed the notes and installed the selenium and geckodriver.

**Comment by ex0dus-0x** [comment]
Try running brut3k1t in a `virtualenv`.

This way, you will have a developmental container that will not interfere with the system's Python. Again, make sure to use `sudo`. 

    pip install virtualenv
    virtualenv brut3k1t-env
    source brut3k1t-env/bin/activate
    python installer.py

I won't go deeply in how `virtualenv` works, and I assume you may have the prerequisites of it down. 
If not, click [here](http://docs.python-guide.org/en/latest/dev/virtualenvs/).
