### ISSUE TITLE
OOPs, something went wrong. Did you terminate the connection? 

### ISSUE THREAD

**Issue by ksalreqabi** [ex0dus-0x/brut3k1t#34]
[*] Username: **
[*] Wordlist: wordlist.txt 
[*] Service: twitter 
[*] Checking if username exists...
[*] Username found! Continuing...
[!] OOPs, something went wrong. Did you terminate the connection? [!]

**Comment by ksalreqabi** [comment]
```
[*] Username: k2 
[*] Wordlist: wordlist.txt 
[*] Service: twitter 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 203, in <module>
    main()
  File "brut3k1t.py", line 152, in main
    if twitUserCheck(username) == 1:
  File "src/twitterLib.py", line 19, in twitUserCheck
    driver = webdriver.Firefox()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/mv/vmxm5p212k765gm1fyym1wjc0000gn/T/tmp4V0IUM If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by ex0dus-0x** [comment]
What is your operating system? You should install/reinstall selenium. 

Three options:

    apt install python-selenium
    pip install -U selenium
    easy_install selenium

**Comment by ksalreqabi** [comment]
Khallids-MacBook-Pro:brut3k1t-master ksalreqabi$ python brut3k1t.py -s twitter -u khalid -w wordlist.txt


o
 \_/\o
( Oo)
(_=-)  .===O-  ~~Z~A~P~~ ~~Z~A~P~~
/   \_/U'
|
||  |_/     Stupid script kiddies!
\   |
{K ||
 | PP
 | ||
 (__\/

Welcome to brut3k1t!


[*] Username: khalid
[*] Wordlist: wordlist.txt 
[*] Service: twitter 
[*] Checking if username exists...
[*] Username found! Continuing...
[!] OOPs, something went wrong. Did you terminate the connection? [!]

**Comment by ex0dus-0x** [comment]
It seems that you are using a mac. Is firefox installed?

**Comment by ex0dus-0x** [comment]
Closed due to inactivity
