### ISSUE TITLE
Traceback (most recent call last):   File "brut3k1t.py", line 2, in <module>     from src.mainLib import *   File "/root/brut3k1t/src/mainLib.py", line 25, in <module>     from xmpp import * ImportError: No module named xmpp

### ISSUE THREAD

**Issue by NickVendetta** [ex0dus-0x/brut3k1t#41]
how to install xmpp modules??

**Comment by ex0dus-0x** [comment]
Have you ran `installer.py` yet? Please don't open a new issue if you haven't even bother to read the `README`

**Comment by ex0dus-0x** [comment]
Please don't open an issue if you haven't even bothered to read the `README`.

**Comment by alideni78** [comment]
i read read me all did both of the `sudo apt-get install python-pip` & `sudo pip install -r requirements.txt`
but i get   Traceback (most recent call last):
  File "brut3k1t.py", line 2, in <module>
    from src.mainLib import *
  File "/root/Desktop/brut3k1t-master/src/mainLib.py", line 24, in <module>
    import smtplib, argparse, paramiko, mechanize
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: No module named utils
what i have to do?
