### ISSUE TITLE
Firefox issue (?)

### ISSUE THREAD

**Issue by lykkelille** [ex0dus-0x/brut3k1t#46]
I am trying to crack my own instagram with only the correct password on the list.
But I am getting some sort of firefox error?

[32m[*] Username: *username* [0m
[32m[*] Wordlist: wordlist.txt [0m
[36m[*] Service: instagram
[35m[*] Checking if username exists...[0m
Traceback (most recent call last):
  File "brut3k1t.py", line 147, in <module>
    main()
  File "brut3k1t.py", line 120, in main
    if usercheck(username, service) == 1:
  File "C:\Users\Line\Desktop\brut3k1t\core\web.py", line 34, in usercheck
    driver = webdriver.Firefox()
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "C:\Python27\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: c:\users\line\appdata\local\temp\tmpsw4jig If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by to73m** [comment]
https://github.com/ex0dus-0x/brut3k1t#3-troubleshooting

**Comment by ex0dus-0x** [comment]
It seems you are using Windows. Make sure that Firefox is loaded up as some sort of environmental variable. I recommend using Linux, as I have never tested brut3k1t on Windows.
