### ISSUE TITLE
Service' object has no attribute 'process'" in 

### ISSUE THREAD

**Issue by rootzzz** [ex0dus-0x/brut3k1t#5]
hello,
im using Kali last version , i can\t get this script to work even tho it looks awesome

`root@kali:~/Desktop/brut3k1t#  python brut3k1t.py -s instagram -u rootzz-w wordlist.txt -d 5
[*] Username: rootzz
[*] Wordlist: wordlist.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 189, in <module>
    main()
  File "brut3k1t.py", line 169, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 17, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7fd205445310>> ignored

**Comment by ex0dus-0x** [comment]
Make sure you have Firefox installed rather than the default Iceweasel.

**Comment by ex0dus-0x** [comment]
Did some updating. Will push repository soon.
    
    sudo apt-get update
    sudo pip uninstall python-selenium
    sudo apt-get install python-selenium firefoxdriver

Try again with that.

**Comment by ex0dus-0x** [comment]
Closing due to inactivity. Also rewrote installer script. To update your repo:

    git pull

or reclone.
