### ISSUE TITLE
Traceback (most recent call last): File "brut3k1t", line 31, in main() File "brut3k1t", line 24, in main WebBruteforce(b.service, b.username, b.

### ISSUE THREAD

**Issue by Shaggy1337** [ex0dus-0x/brut3k1t#50]
Traceback (most recent call last):
  File "brut3k1t", line 31, in <module>
    main()
  File "brut3k1t", line 24, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by Shaggy1337** [comment]
This is why Python-selenium is Omitted
 But this is the opposite / brut3k1t # ./brut3k1t
[!] You have to specify a username AND a wordlist! [!]
Root @ kali: ~ / brut3k1t #
