### ISSUE TITLE
Error message on Kali Linux amd64

### ISSUE THREAD

**Issue by ABeater** [ex0dus-0x/brut3k1t#51]
I got this error message on the service instagram:
(some problem with the Browser temp files or what does this(tmp) mean?)

Error caught! Message: Unable to locate element: {"method":"name","selector":"username"}
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmp_aSwbv/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at FirefoxDriver.prototype.findElement (file:///tmp/tmp_aSwbv/extensions/fxdriver@googlecode.com/components/driver-component.js:10779)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmp_aSwbv/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmp_aSwbv/extensions/fxdriver@googlecode.com/components/command-processor.js:12666)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmp_aSwbv/extensions/fxdriver@googlecode.com/components/command-processor.js:12608)

(i didnt find something about it in troubleshooting)

(and a question by the way...where and how did you learn python? i learn python3 with some free online tutorials at the moment...i just want ask if you learn it too there and How long it took for you to be so good ?)

**Comment by nfgn** [comment]
Traceback (most recent call last):
  File "brut3k1t", line 30, in <module>
    main()
  File "brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by ex0dus-0x** [comment]
@nfgn This issue has already been solved. Please look at the `README` in the troubleshooting section.

@ABeater What OS? Have you reinstalling `selenium`? Check if it has been installed through `apt` and try through there. Then uninstall the `selenium` pip module

**Comment by ABeater** [comment]
ok i have Kali Linux AMD 64 and  i installed "selenium" with the command "pip install -U selenium"(i dont know how i can do it with apk..)then i got the error from the user "nfgn" then i copied geckodriver in /usr/bin and /usr/local/bin/(i read this here(https://pypi.python.org/pypi/selenium)) but now i have a new error just : 
Error caught! Message: Unable to locate element: [name="username"]
and the firefox windows do not close themself after it checked the username.  i have then 3 open firefox-windows and the error appears at the firefox-window with the login fields.

**Comment by ABeater** [comment]
EDIT: ok i copied geckodriver again in /usr/local/bin because it was away..i dont know why haha....but it worked now....but has instagram a bruteforce defense because i get the message "there was a problem loggin you into instagram. pls try again soon..." and not the normal message "incorrect..etc" mh but you didnt answer my question where did you learn python ? and sry for some grammatical mistakes...english isnt my native language....

**Comment by ex0dus-0x** [comment]
I set a timeout when that occurs. I have been researching methods to randomize the user agent as well as set a proxy when such an occurrence occurs.
