### ISSUE TITLE
Hahlp

### ISSUE THREAD

**Issue by mxkxx** [ex0dus-0x/brut3k1t#52]
Traceback (most recent call last):
  File "brut3k1t", line 30, in <module>
    main()
  File "brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Escritorio/brut3k1t-master/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Escritorio/brut3k1t-master/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.4.3-py2.7.egg/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by ex0dus-0x** [comment]
Have you read the `README`?
