### ISSUE TITLE
i got this problem 

### ISSUE THREAD

**Issue by tarekxxx** [ex0dus-0x/brut3k1t#54]
it was broweser open for nothing and just close again i upgrade selenium

now says 

[*] Service: facebook 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 30, in <module>
    main()
  File "./brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Desktop/brut3k1t/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Desktop/brut3k1t/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by ex0dus-0x** [comment]
Have you read the `README`?
