### ISSUE TITLE
Still getting "geckodriver not in path" error

### ISSUE THREAD

**Issue by HackingBegginer527** [ex0dus-0x/brut3k1t#58]
Hi there,
I am a begginer to coding and hacking and really have no idea on how to fix this problem, I keep getting the error "Traceback (most recent call last):
  File "./brut3k1t", line 30, in <module>
    main()
  File "./brut3k1t", line 23, in main
    WebBruteforce(b.service, b.username, b.wordlist, b.delay)
  File "/root/Desktop/brut3k1t-master/core/web.py", line 38, in __init__
    self.usercheck(self.username, self.service)
  File "/root/Desktop/brut3k1t-master/core/web.py", line 47, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 142, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. " and I was in your troubleshoot settings and did all of those steps at least twice and its still not working.... please get back to me as soon as possible, thank you so much and have a good one!

**Comment by ex0dus-0x** [comment]
Fixed. `git update`
