### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by coolneb** [ex0dus-0x/brut3k1t#65]
Getting this issue.. Any fixes??

Traceback (most recent call last):
  File "./brut3k1t", line 87, in <module>
    main()
  File "./brut3k1t", line 76, in main
    w.execute()
  File "/root/Desktop/brut3k1t/core/web.py", line 39, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t/core/web.py", line 48, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by ex0dus-0x** [comment]
Check the `README`, and try to manually place `geckodriver` in your `PATH`.

This issue has been covered numerously. Check previous issues.
