### ISSUE TITLE
New Error!

### ISSUE THREAD

**Issue by NexifyUS** [ex0dus-0x/brut3k1t#68]
I AM USING KALI LINUX 2017.1 I HAVE TOR AND FIREFOX INSTALLED!

Traceback (most recent call last):
  File "./brut3k1t", line 87, in <module>
    main()
  File "./brut3k1t", line 76, in main
    w.execute()
  File "/root/Desktop/brut3k1t/core/web.py", line 39, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t/core/web.py", line 48, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

**Comment by ex0dus-0x** [comment]
Please provide OS version, as well as browser. Please make sure you are utilizing Firefox.

**Comment by NexifyUS** [comment]
i am using the firefox browser and im on the latest version 2017.1 kali linux

**Comment by NexifyUS** [comment]
Has anyone else had this problem?

**Comment by NexifyUS** [comment]
@ex0dus-0x I updated the new error i get now

**Comment by ex0dus-0x** [comment]
Try to reinstall `selenium`. If it is installed through `apt`, uninstall it and use `pip`. Inversely, if it is installed through `pip`, uninstall and install through `apt`.

**Comment by NexifyUS** [comment]
@ex0dus-0x its still not working im a bit confused

**Comment by ex0dus-0x** [comment]
Have you read the `README` before consulting?

**Comment by NexifyUS** [comment]
@ex0dus-0x i have. i also listened to what you said before i uninstalled through apt and pip and installed throught apt it didnt work then uninstalled that and tried pip still didnt wokr

**Comment by ex0dus-0x** [comment]
Try updating Firefox. (Reference [here](https://stackoverflow.com/questions/43713445/selenium-unable-to-find-a-matching-set-of-capabilities-despite-driver-being-in))

The current version of `geckodriver` being used by brut3k1t is 0.18.

See also: https://github.com/SeleniumHQ/selenium/issues/3884
