### ISSUE TITLE
i have this problem

### ISSUE THREAD

**Issue by gsquared19** [ex0dus-0x/brut3k1t#69]
File "brut3k1t", line 87, in <module>
    main()
  File "brut3k1t", line 76, in main
    w.execute()
  File "/Users/georgegkogkos/Downloads/brut3k1t-master/core/web.py", line 39, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/Users/georgegkogkos/Downloads/brut3k1t-master/core/web.py", line 48, in usercheck
    driver = webdriver.Firefox()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.5.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-3.5.0-py2.7.egg/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by ex0dus-0x** [comment]
Please read `README`. Make sure that the `geckodriver` executable, which comes with the repository, is placed within your `PATH`.

**Comment by Tawbin-Raif** [comment]
i have the same problem 
how can i fix it?
Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-i686/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-i686/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-3.14.1-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
