### ISSUE TITLE
Error on Kali Linux & Ubuntu tried them 2 and still receive this.. 

### ISSUE THREAD

**Issue by TwistedLobby** [ex0dus-0x/brut3k1t#7]
[*] Username: stank_tank35 
[*] Wordlist: rockyou.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 190, in <module>
    main()
  File "brut3k1t.py", line 159, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 20, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f73e2bbc750>> ignored

**Comment by ex0dus-0x** [comment]
Hello,

I have done some updating to the code. Please execute:

    git pull

or reclone the repository using 

    git clone https://github.com/ex0dus-0x/brut3k1t

There is an installer file that I've written. I have not tested it extensively yet. However, try it out. If it does not work. execute this:

    sudo apt-get install python-selenium firefoxdriver firefox-esr

If there is no package called `python-selenium`, try:

     sudo easy_install selenium

**Comment by TwistedLobby** [comment]
Still seem to be receiving this error on Kali Linux

> *] Username: stank_tank35 
[*] Wordlist: rockyou.txt 
[*] Service: instagram 
[*] Checking if username exists...
Traceback (most recent call last):
  File "brut3k1t.py", line 190, in <module>
    main()
  File "brut3k1t.py", line 159, in main
    if instUserCheck(username) == 1:
  File "src/instagramLib.py", line 20, in instUserCheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x7f603ee8c750>> ignored

**Comment by ex0dus-0x** [comment]
Try:

    sudo apt-get update

This will update your repositories. Then attempt to do that again.

Have you tried out the installation script as well? It will automate this process.

**Comment by TwistedLobby** [comment]
Yes, I'll check and see.

**Comment by TwistedLobby** [comment]
Still receive the error on Ubuntu.

**Comment by ex0dus-0x** [comment]
Rewrote installer script. Try to install dependencies with that. To update your repo:

    git pull

or reclone.

**Comment by TwistedLobby** [comment]
Now receiving

```
Traceback (most recent call last):
  File "brut3k1t.py", line 14, in <module>
    from mainLib import *
  File "src/mainLib.py", line 23, in <module>
    import smtplib, argparse, paramiko, skpy
ImportError: No module named skpy

```

**Comment by ex0dus-0x** [comment]
pip install skpy

Oops forgot to add that in my installer script, since its a newly installed module for skype bruteforcing.

**Comment by TwistedLobby** [comment]
Ok

**Comment by ex0dus-0x** [comment]
Ignore prior comment. If `pip install skpy` did not work, I did a rewrite of the entire script again.

    git pull

or reclone. Then run the `installer.py` file.

    sudo python installer.py

**Comment by ex0dus-0x** [comment]
Closing due to inactivity

I've made updates. 

    git pull

or reclone.
