### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message

### ISSUE THREAD

**Issue by yassery777** [ex0dus-0x/brut3k1t#77]
hi
thank you for your program.

i set delay to 5 seconds and the program guess the wrong password because too attempting to enter instagram cause error by instagram.    ):
!

thanks a lot.
sorry again.
GOOD LUCK.

**Comment by ex0dus-0x** [comment]
This does not help. Please give error messages, and steps to reproduce.

**Comment by sadlybadly** [comment]
Traceback (most recent call last):
  File "brut3k1t", line 77, in <module>
    main()
  File "brut3k1t", line 70, in main
    w.execute()
  File "/usr/share/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/usr/share/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities

**Comment by Juniorn1003** [comment]
I made a better version of Facebook/Twitter/Instagram Bruteforce script, come check it out.
brut3-k1t is not ready for bruteforcing yet, it has no proxy at all.
https://github.com/Juniorn1003/Faitagram

**Comment by coalcarter** [comment]
hi
i have a error
this is my error ImportError: No module named selenium
what's wrong?
