### ISSUE TITLE
Text color in Terminal did not change back to black in Mac OS X

### ISSUE THREAD

**Issue by ssysm** [ex0dus-0x/brut3k1t#8]
Get error
mkdir: /opt: No such file or directory
Traceback (most recent call last):
  File "installer.py", line 79, in <module>
    osx_build()
  File "installer.py", line 64, in osx_build
    os.symlink("/usr/bin/brut3k1t", "/opt/brut3k1t/brut3k1t.py")
OSError: [Errno 2] No such file or directory

After Error terminal stay at dark yellow.

Python Run at:3.5.2 Max OS X

**Comment by ex0dus-0x** [comment]
Will fix. Thanks for finding the error. OS X build is not yet complete. However, if you do want to build for OS X, follow these instructions (assuming you have brew and brew cast already):
   
    brew cast install firefox
    sudo easy_install pip selenium
    sudo pip install -r requirements.txt
    
I will be pushing changes approximately tomorrow. From there, the OS X build should work, as this was an incomplete installation script. Thanks!

**Comment by ex0dus-0x** [comment]
Changes are pushed. Closing due to inactivity
