### ISSUE TITLE
Can't run brut3k1t (error)

### ISSUE THREAD

**Issue by asciiterminal** [ex0dus-0x/brut3k1t#88]
when i try to initialize brut3k1t using `./brut3k1t -h` i get this error 

```
Traceback (most recent call last):
  File "./brut3k1t", line 2, in <module>
    from src import *
  File "/root/brut3k1t/src/__init__.py", line 2, in <module>
    from . import main
  File "/root/brut3k1t/src/main.py", line 16, in <module>
    from xmpp import Client
ImportError: No module named xmpp

```

**Comment by thistehneisen** [comment]
+1

**Comment by thistehneisen** [comment]
@asciiterminal just do this:
┌─[✗]─[seq@parrot]─[~/Code/Python/brut3k1t]
└──╼ $pip install xmpppy

**Comment by Nicholasjaar** [comment]
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/desktop/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/desktop/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error


help meee !!
