### ISSUE TITLE
 Error after pip 

### ISSUE THREAD

**Issue by ssysm** [ex0dus-0x/brut3k1t#9]
`Traceback (most recent call last):
  File "brut3k1t.py", line 14, in <module>
    from mainLib import *
  File "src/mainLib.py", line 24, in <module>
    import smtplib, argparse, paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: No module named cryptography.hazmat.backends
`
Is there any solution for this?

**Comment by ex0dus-0x** [comment]
sudo pip install crytography

If that doesn't work, try 

    sudo easy_install crytography

**Comment by ssysm** [comment]
Ok Thanks
