### ISSUE TITLE
what the solve

### ISSUE THREAD

**Issue by ghabnawe** [ex0dus-0x/brut3k1t#91]
[*] Wordlist: wordlist.txt 
[*] Service: twitter 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/Desktop/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by newbieModz** [comment]
@swirldapimp i have tried your suggestion but i get this problem (below)

In [1]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:browser = None          
:def StartSelenium():
:import selenium
:from selenium import webdriver
:from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
:import binascii
:import hashlib
:firefox_capabilities = DesiredCapabilities.FIREFOX
:firefox_capabilities['marionette'] = True
:firefox_capabilities['binary'] = '/usr/bin/firefox'
:global browser
:browser = webdriver.Firefox(capabilities=firefox_capabilities)
:browser.get('https://www.google.com')
:--
  File "<ipython-input-1-b5148e1b2187>", line 3
    import selenium
         ^
IndentationError: expected an indented block


In [2]:

**Comment by Khaliddxx** [comment]
Just indent 
import selenium
by pressing TAB before it
