### ISSUE TITLE
Your Firefox profile cannot be loaded. It may be missing or inaccessible.

### ISSUE THREAD

**Issue by skr325** [ex0dus-0x/brut3k1t#92]
os : parrot os 
Firefox 59.0.1 (64-bit)

[*] Service: facebook 
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/crack/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/crack/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1

on Facebook and instagram and twitter
any help?

**Comment by KapitainJames** [comment]
Same problem on Parrot OS. I tried installing geckodrivers.
