### ISSUE TITLE
Please help me with this problem

### ISSUE THREAD

**Issue by abkreno2530** [ex0dus-0x/brut3k1t#97]
_                _   _____ _    _ _
 | |__  _ __ _   _| |_|___ /| | _/ | |_
 | '_ \| '__| | | | __| |_ \| |/ / | __|
 | |_) | |  | |_| | |_ ___) |   <| | |_
 |_.__/|_|   \__,_|\__|____/|_|\_\_|\__|
    Written by: @ex0dus-0x
 
[*] Username: redax1250@gmail.com 
[*] Wordlist: /media/root/D424D5CB24D5B12A/pass1.txt 
[*] Service: facebook 
[?] Delay not set! Default to 1 [?]
[*] Checking if username exists...
Traceback (most recent call last):
  File "./brut3k1t", line 98, in <module>
    main()
  File "./brut3k1t", line 86, in main
    w.execute()
  File "/root/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Believe me I have tried to search all topics for a solution to this problem without interest Please help if you can not tell me instead of waiting and thank you very much in all cases

**Comment by ex0dus-0x** [comment]
Reinstall `selenium`. This is not an application-level issue.

Also check: https://github.com/ex0dus-0x/brut3k1t/issues/101
