### ISSUE TITLE
Hello, I have problem, error. Please help if u can with something.

### ISSUE THREAD

**Issue by iHaveAProblem27** [ex0dus-0x/brut3k1t#98]
I have this error when I use this command: python brut3k1t -s facebook -u ID -w wordlist.txt -d 1

Traceback (most recent call last):
  File "brut3k1t", line 98, in <module>
    main()
  File "brut3k1t", line 86, in main
    w.execute()
  File "/root/Desktop/brut3k1t/core/web.py", line 42, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "/root/Desktop/brut3k1t/core/web.py", line 51, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

If some one can help please tell me.
Best Regards
Thanks in future

**Comment by ex0dus-0x** [comment]
https://github.com/ex0dus-0x/brut3k1t/issues/101
